//login form
(function(){dust.register("login",body_0);function body_0(chk,ctx){return chk.write("<div class=\"toolbar\"><span class=\"cancel-link\" href=\"#\">Cancel</span><h1>Log In</h1></div><div class=\"login-form input-form\"><div class=\"form-container\"><div class=\"message\"></div><form id=\"login-form\" action=\"\" method=\"post\"><label for=\"login-login\">Author Name</label><input id=\"login-login\" type=\"text\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"login-password\">Password</label><input id=\"login-password\" type=\"password\" name=\"password\" value=\"\"/></form><input id=\"login-submit\" class=\"submit-button\" type=\"submit\" value=\"Log In\" /><a id=\"create-user-link\" href=\"/newuser\">Need an account? Sign Up!</a></div></div>");}return body_0;})();

//new user form
(function(){dust.register("newuser",body_0);function body_0(chk,ctx){return chk.write("<div class=\"toolbar\"><span class=\"cancel-link\" href=\"#\">Cancel</span><h1>Create New User</h1></div><div class=\"newuser-form input-form\"><div class=\"form-container\"><div class=\"message\"></div><form id=\"newuser-form\" action=\"\" method=\"post\"><label for=\"newuser-name\">Author Name</label><input id=\"newuser-name\" type=\"text\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"newuser-fullname\">Full Name</label><input id=\"newuser-fullname\" type=\"text\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"newuser-email\">Email</label><input id=\"newuser-email\" type=\"email\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"newuser-password\">Password</label><input id=\"newuser-password\" type=\"password\" name=\"password\" value=\"\"/></form><input id=\"newuser-submit\" class=\"submit-button\" type=\"submit\" value=\"Create\" /><a id=\"login-link\" href=\"/newuser\">Already have an account? Sign In!</a></div></div>");}return body_0;})();

//settings templates
(function(){dust.register("settings",body_0);function body_0(chk,ctx){return chk.write("<div class=\"toolbar\"><span class=\"cancel-link\" href=\"#\">Back</span><h1>Settings</h1></div><div class=\"settings-container split-pane\"><nav class=\"side-tabs\"><ul><li class=\"profile-tab\"></li><li class=\"services-tab\"></li><li class=\"features-tab\"></li></ul><a id=\"logout-link\">log out</a></nav><div class=\"main-content\">").partial("_profileEdit",ctx).partial("_services",ctx).partial("_authorFeatures",ctx).write("</div></div>");}return body_0;})();
(function(){dust.register("_services",body_0);function body_0(chk,ctx){return chk.write("<div class=\"services-form settings-form tab-content\"><h3>Add/Remove Accounts for ").reference(ctx.get("name"),ctx,"h").write("</h3><ul>").section(ctx.get("services"),ctx,{"block":body_1},null).write("</ul><form id=\"services-form\" method=\"POST\"></form></div>");}function body_1(chk,ctx){return chk.write("<li class=\"").reference(ctx.get("name"),ctx,"h").write(" ").reference(ctx.get("enabled"),ctx,"h").write("\"> ").reference(ctx.get("name"),ctx,"h").write(" <a class=\"activate\" href=\"").reference(ctx.get("url"),ctx,"h").write("\">activate</a><span class=\"deactivate\">active</span></li>");}return body_0;})();
(function(){dust.register("_profileEdit",body_0);function body_0(chk,ctx){return chk.write("<div class=\"edit-profile-form tab-content\"><h3>Edit Profile for ").reference(ctx.get("name"),ctx,"h").write("</h3><div class=\"profile-form input-form\"><div class=\"form-container\"> <div class=\"message display-none\"></div><form id=\"edit-profile-form\" method=\"POST\"><label for=\"edit-profile-fullname\">Full Name</label><input id=\"edit-profile-fullname\" type=\"text\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"edit-profile-email\">Email</label><input id=\"edit-profile-email\" type=\"email\" autocapitalize=\"off\" autocorrect=\"off\" autocomplete=\"off\" name=\"login\" value=\"\"/><label for=\"edit-profile-password\">Password</label><input id=\"edit-profile-password\" type=\"password\" name=\"password\" value=\"\"/></form><input id=\"edit-profile-submit\" class=\"submit-button\" type=\"submit\" value=\"Save\" /></div></div></div>");}return body_0;})();
(function(){dust.register("_authorFeatures",body_0);function body_0(chk,ctx){return chk.write("<div class=\"features-form tab-content settings-form\"><h3>Add/Remove Features for ").reference(ctx.get("name"),ctx,"h").write("</h3><ul>").section(ctx.get("features"),ctx,{"block":body_1},null).write("</ul><form id=\"features-form\" method=\"POST\"></form></div>");}function body_1(chk,ctx){return chk.write("<li class=\"").reference(ctx.get("name"),ctx,"h").write(" ").reference(ctx.get("enabled"),ctx,"h").write("\"> ").reference(ctx.get("name"),ctx,"h").write(" <a class=\"activate\" data-feature-name=\"").reference(ctx.get("name"),ctx,"h").write("\" href=\"").reference(ctx.get("url"),ctx,"h").write("\">activate</a><span class=\"deactivate\">active</span></li>");}return body_0;})();

//general 'app' templates
(function(){dust.register("featureNavItem",body_0);function body_0(chk,ctx){return chk.write("<a href=\"").reference(ctx.get("path"),ctx,"h").write("\">").reference(ctx.get("name"),ctx,"h").write("</a>");}return body_0;})();
(function(){dust.register("toolbar",body_0);function body_0(chk,ctx){return chk.section(ctx.get("items"),ctx,{"block":body_1},null);}function body_1(chk,ctx){return chk.write("<span class=\"").reference(ctx.get("name"),ctx,"h").write("\" data-toolbar-item=\"").reference(ctx.get("name"),ctx,"h").write("\"/>");}return body_0;})();
(function(){dust.register("flipPage",body_0);function body_0(chk,ctx){return chk.write("<div class=\"page flip-").reference(ctx.get("pageNum"),ctx,"h").write("\" data-num=\"").reference(ctx.get("pageNum"),ctx,"h").write("\" style=\"z-index:").reference(ctx.get("zIndex"),ctx,"h").write("\"><div class=\"front\"><div class=\"outer\"><div class=\"content\" style=\"\"><div class=\"inner\">").reference(ctx.get("frontContent"),ctx,"h",["s"]).write("</div></div></div></div><div class=\"back\"><div class=\"outer\"><div class=\"content\" style=\"\"><div class=\"inner\">").reference(ctx.get("backContent"),ctx,"h",["s"]).write("</div></div></div></div></div>");}return body_0;})();
(function(){dust.register("commentList",body_0);function body_0(chk,ctx){return chk.exists(ctx.get("toolbar"),ctx,{"block":body_1},null).write("<div class=\"split-pane\"><ul class=\"service-tabs\">").section(ctx.get("sources"),ctx,{"block":body_2},null).write("</ul><div class=\"comments scrollable\"><div class=\"scroll-inner\">").section(ctx.get("comments"),ctx,{"block":body_3},null).write("</div></div></div>");}function body_1(chk,ctx){return chk.write("<div class=\"toolbar\"><span class=\"back-link\" data-toolbar-item=\"back-link\"/><h1>Comments</h1></div>");}function body_2(chk,ctx){return chk.write("<li class=\"").reference(ctx.get("source_name"),ctx,"h").write(" ").reference(ctx.get("selected"),ctx,"h").write("\"></li>");}function body_3(chk,ctx){return chk.write("<div class=\"comment\"><div class=\"user-thumb\"></div><div class=\"info\"><div class=\"user-name\">").reference(ctx.get("authorName"),ctx,"h").write("<span class=\"time-ago\">").reference(ctx.get("time"),ctx,"h").write("</span></div><div class=\"text\">").reference(ctx.get("text"),ctx,"h",["s"]).write("</div></div></div>");}return body_0;})();
(function(){dust.register("_eventFooter",body_0);function body_0(chk,ctx){return chk.write("<footer><div class=\"main-text\">").exists(ctx.get("tagline"),ctx,{"block":body_1},null).exists(ctx.get("caption_text"),ctx,{"block":body_2},null).write("</div><div class=\"avatar\"><div class=\"frame\"><img src=\"").reference(ctx.getPath(false,["author","picture","image_url"]),ctx,"h").write("\"/></div></div><div class=\"author\"><a href=\"/").reference(ctx.getPath(false,["author","name"]),ctx,"h").write("/#timeline\">").reference(ctx.getPath(false,["author","full_name"]),ctx,"h").write("</a></div>\t\t  <div class=\"sources\"><!-- loop through sources -->").exists(ctx.getPath(false,["origin","known"]),ctx,{"block":body_3},null).exists(ctx.getPath(false,["origin","unknown"]),ctx,{"block":body_5},null).write("<span class=\"time-and-location\">").reference(ctx.get("time_ago"),ctx,"h").write(" ").reference(ctx.getPath(false,["location","name"]),ctx,"h").write("</span></div><div class=\"interaction-icons\"><span class=\"location\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"></span><span class=\"comments\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"></span></div></footer>");}function body_1(chk,ctx){return chk.reference(ctx.get("tagline"),ctx,"h");}function body_2(chk,ctx){return chk.reference(ctx.get("caption_text"),ctx,"h");}function body_3(chk,ctx){return chk.write(" ").exists(ctx.getPath(false,["origin","known","service_name"]),ctx,{"block":body_4},null);}function body_4(chk,ctx){return chk.write("<img class=\"service-icon\" src=\"").reference(ctx.get("footer_img"),ctx,"h").write("\"/>");}function body_5(chk,ctx){return chk.write("<img class=\"service-icon\" src=\"").reference(ctx.getPath(false,["origin","unknown","small_icon"]),ctx,"h").write("\"/>");}return body_0;})();
(function(){dust.register("photoPage",body_0);function body_0(chk,ctx){return chk.write("<div class=\"photo-page\"><div class=\"toolbar\"><span class=\"grid-link\" data-toolbar-item=\"grid-link\"/><h1>").reference(ctx.get("num"),ctx,"h").write(" of ").reference(ctx.getPath(false,["options","pageMetaData","count"]),ctx,"h").write("</h1></div>").section(ctx.get("events"),ctx,{"block":body_1},null).write("</div>");}function body_1(chk,ctx){return chk.section(ctx.get("main_image"),ctx,{"block":body_2},null).partial("_eventFooter",ctx).write("<div class=\"interaction-icons\"><span class=\"location\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"></span><span class=\"comments\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"></span></div>");}function body_2(chk,ctx){return chk.write("<div class=\"full-photo\" style=\"background-image:url(").reference(ctx.get("image_url"),ctx,"h").write(")\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"/>");}return body_0;})();
(function(){dust.register("timelinePage",body_0);function body_0(chk,ctx){return chk.write("<div class=\"toolbar\"><h1>News</h1></div><div class=\"mi-content\"  style=\"height: 100%;\">").section(ctx.get("events"),ctx,{"block":body_1},null).write("</div>");}function body_1(chk,ctx){return chk.write("<div class=\"event ").reference(ctx.get("event_class"),ctx,"h").write("\" data-event_id=\"").reference(ctx.get("id"),ctx,"h").write("\">").partial(body_2,ctx).write("</div>");}function body_2(chk,ctx){return chk.reference(ctx.get("event_template"),ctx,"h");}return body_0;})();

//moving timeline templates to global templates file
(function(){dust.register("_event",body_0);function body_0(chk,ctx){return chk.write("<div class=\"content\">").exists(ctx.get("photo"),ctx,{"else":body_1,"block":body_2},null).write("<div class=\"inner-text\">").exists(ctx.get("headline"),ctx,{"block":body_3},null).exists(ctx.get("content"),ctx,{"block":body_4},null).write("</div></div>").partial("_eventFooter",ctx);}function body_1(chk,ctx){return chk;}function body_2(chk,ctx){return chk.write("<div class=\"inner-image\"><img src='").reference(ctx.getPath(false,["photo","image_url"]),ctx,"h").write("' /></div>");}function body_3(chk,ctx){return chk.write("<p>").reference(ctx.get("headline"),ctx,"h").write("</p>");}function body_4(chk,ctx){return chk.write("<p>").reference(ctx.get("content"),ctx,"h").write("</p>");}return body_0;})();
(function(){dust.register("page",body_0);function body_0(chk,ctx){return chk.write("<div class=\"mi-content\" style=\"height: 100%;\">").section(ctx.get("events"),ctx,{"block":body_1},null).write("</div>");}function body_1(chk,ctx){return chk.write("<div class=\"event half-page\" data-event_id=\"").reference(ctx.get("event_id"),ctx,"h").write("\">").partial("_event",ctx).write("</div>");}return body_0;})();
(function(){dust.register("eventDetail",body_0);function body_0(chk,ctx){return chk.write("<div class=\"eventDetail\">DETAIL VIEW FOR TIMELINE EVENT!").section(ctx.get("content"),ctx,{"block":body_1},null).write("</div>");}function body_1(chk,ctx){return chk.write("<div class=\"content\">").exists(ctx.get("photo_url"),ctx,{"else":body_2,"block":body_3},null).write("<div class=\"inner-text\"><p>").reference(ctx.get("data"),ctx,"h").write("</p></div></div>");}function body_2(chk,ctx){return chk;}function body_3(chk,ctx){return chk.write("<div class=\"inner-image\"><img src='").reference(ctx.get("photo_url"),ctx,"h").write("' /></div>");}return body_0;})();

//event/post types
(function(){dust.register("_photo",body_0);function body_0(chk,ctx){return chk.write("<img class=\"thumb\" src=\"http://farm").reference(ctx.get("farm"),ctx,"h").write(".static.flickr.com/").reference(ctx.get("server"),ctx,"h").write("/").reference(ctx.get("id"),ctx,"h").write("_").reference(ctx.get("secret"),ctx,"h").write("_s.jpg\" data-photo_id=\"").reference(ctx.get("id"),ctx,"h").write("\"/>");}return body_0;})();
(function(){dust.register("_follow",body_0);function body_0(chk,ctx){return chk.write(" <div class=\"content follow\">").exists(ctx.get("photo"),ctx,{"else":body_1,"block":body_2},null).write("<div class=\"inner-text\">").exists(ctx.get("headline"),ctx,{"block":body_3},null).exists(ctx.get("content"),ctx,{"block":body_4},null).write("</div></div>").partial("_eventFooter",ctx);}function body_1(chk,ctx){return chk;}function body_2(chk,ctx){return chk.write("<div class=\"inner-image\"><img src='").reference(ctx.getPath(false,["photo","image_url"]),ctx,"h").write("' /></div>");}function body_3(chk,ctx){return chk.write("<p>").reference(ctx.get("headline"),ctx,"h").write("</p>");}function body_4(chk,ctx){return chk.write("<p>").reference(ctx.get("content"),ctx,"h").write("</p>");}return body_0;})();
(function(){dust.register("_checkin",body_0);function body_0(chk,ctx){return chk.write(" <div class=\"content checkin\">").exists(ctx.get("photo"),ctx,{"else":body_1,"block":body_2},null).write("<div class=\"inner-text\">").exists(ctx.get("headline"),ctx,{"block":body_3},null).exists(ctx.get("content"),ctx,{"block":body_4},null).write("</div></div>").partial("_eventFooter",ctx);}function body_1(chk,ctx){return chk;}function body_2(chk,ctx){return chk.write("<div class=\"inner-image\"><img src='").reference(ctx.getPath(false,["photo","image_url"]),ctx,"h").write("' /></div>");}function body_3(chk,ctx){return chk.write("<p>").reference(ctx.get("headline"),ctx,"h").write("</p>");}function body_4(chk,ctx){return chk.write("<p>").reference(ctx.get("content"),ctx,"h").write("</p>");}return body_0;})();
(function(){dust.register("_photoAlbum",body_0);function body_0(chk,ctx){return chk.write(" <div class=\"content photo-album\">").exists(ctx.get("primary_image"),ctx,{"else":body_1,"block":body_2},null).write("<div class=\"inner-text\">").exists(ctx.get("headline"),ctx,{"block":body_3},null).exists(ctx.get("content"),ctx,{"block":body_4},null).write("</div></div>").partial("_eventFooter",ctx);}function body_1(chk,ctx){return chk;}function body_2(chk,ctx){return chk.write("<div class=\"inner-image\"><img src='").reference(ctx.getPath(false,["primary_image","image_url"]),ctx,"h").write("' /></div>");}function body_3(chk,ctx){return chk.write("<p>").reference(ctx.get("headline"),ctx,"h").write("</p>");}function body_4(chk,ctx){return chk.write("<p>").reference(ctx.get("content"),ctx,"h").write("</p>");}return body_0;})();

//the author list for the index page
(function(){dust.register("authorList",body_0);function body_0(chk,ctx){return chk.write("<ul>").section(ctx.get("authors"),ctx,{"block":body_1},null).write("</ul>").section(ctx.get("authors"),ctx,{"else":body_2,"block":body_3},null);}function body_1(chk,ctx){return chk.write("<li><a href=\"").reference(ctx.get("author_name"),ctx,"h").write("\" data-author_name=\"").reference(ctx.get("author_name"),ctx,"h").write("\"><img src=\"/").reference(ctx.get("author_name"),ctx,"h").write("/asset/profile_thumb.jpg\"/><span>").reference(ctx.get("full_name"),ctx,"h").write("</span></a></li>");}function body_2(chk,ctx){return chk.write("<div class=\"no-authors\">No Authors</div>");}function body_3(chk,ctx){return chk;}return body_0;})();

(function(){
  //put global dust helper fns here
  
  function renderParameter(name, chunk, context, bodies, params) {
  	if (params && params[name]) {
  		if (typeof params[name] === "function") {
  			var output = "";
  			chunk.tap(function (data) {
  				output += data;
  				return "";
  			}).render(params[name], context).untap();
  			return output;
  		} else {
  			return params[name];
  		}
  	}
  	return "";
  }

  dust.helpers.truncate = function(chunk, context, bodies, params) {
    var str = renderParameter("value", chunk, context, bodies, params);
    var length = params.length || 15;
    if (str.length > length) {
      chunk.write(str.substring(0,length) + "...");
    } else {
      chunk.write(str);
    }
    return chunk;
  }

})()

/* maybe put a fn to render 'friendly time' here? */